let lightMode = document.getElementById('lightModeBtn')
let darkMode = document.getElementById('darkModeBtn')
let lightModeAlert = document.getElementById('lightModeAlert')
let darkModeAlert = document.getElementById('darkModeAlert')
darkMode.addEventListener("click", function () {
    document.documentElement.setAttribute('data-bs-theme', 'dark')
    lightMode.classList.remove('d-none')
    darkMode.classList.add('d-none')
    lightModeAlert.classList.add('d-none')
    darkModeAlert.classList.remove('d-none')
})
lightMode.addEventListener("click", function () {
    document.documentElement.setAttribute('data-bs-theme', 'light')
    darkMode.classList.remove('d-none')
    lightMode.classList.add('d-none')
    darkModeAlert.classList.add('d-none')
    lightModeAlert.classList.remove('d-none')
})